### ISSUE TITLE
In app reviews used to show up but not anymore

### ISSUE THREAD

**Issue by toplay3** [cengiz-pz/godot-android-inapp-review-plugin#2]
How does this plugin work?

Does plugin need to know which app on the play store it is supposed to review? Because I didn't need to put the app id anywhere.

Maybe I'm missing a step, with most plugins, I need to drag something into the android/plugins folder and enable it in the export settings, do I need to do this here?

**Comment by cengiz-pz** [comment]
Hi @toplay3,

In order for the plugin to work, the first requirement is that the application needs to be registered with Google Play (ie. not an unregistered demo/test app).

Additionally, there is a per-user per-app limitation that Google enforces on the review requests:

> To provide a great user experience, Google Play enforces a time-bound quota on how often a user can be shown the review dialog. Because of this quota, calling the launchReviewFlow method more than once during a short period of time (for example, less than a month) might not always display a dialog.

More: https://developer.android.com/guide/playcore/in-app-review#quotas

Thanks for using the plugin

**Comment by toplay3** [comment]
> Hi @toplay3,
> 
> In order for the plugin to work, the first requirement is that the application needs to be registered with Google Play (ie. not an unregistered demo/test app).
> 
> Additionally, there is a per-user per-app limitation that Google enforces on the review requests:
> 
> > To provide a great user experience, Google Play enforces a time-bound quota on how often a user can be shown the review dialog. Because of this quota, calling the launchReviewFlow method more than once during a short period of time (for example, less than a month) might not always display a dialog.
> 
> More: https://developer.android.com/guide/playcore/in-app-review#quotas
> 
> Thanks for using the plugin

Oh I see, yep that makes sense I just hit the quota, adb logcat didn't show anything but on another account it showed up again.

Thanks

**Comment by durdenk** [comment]
I can use in app purchases and admon ads and everything using my phone connected to my computer via usb cable,
My app in close testing status right now, so it is not public but registered.

Can I test this plugin like tthat way? Deploying via a usb cable?

My review plugin doesnt work , all the signals are beeing fired one after another, I dont see a dialog . I wonder if that is the reason.

**Comment by cengiz-pz** [comment]
Hi @durdenk, are there any clues in the logs (`adb logcat`)?
